// laenderCategory.js

export const laenderKategorien = {
  "Brasilien": "Schwellenland",
  "Belgien": "Industrieland",
  "Dänemark": "Industrieland",
  "Frankreich": "Industrieland",
  "Luxemburg": "Industrieland",
  "Monaco": "Industrieland",
  "Niederlande": "Industrieland",
  "Österreich": "Industrieland",
  "Polen": "Schwellenland",
  "Tschechische Republik": "Schwellenland",
  "Liechtenstein": "Industrieland",
  "Schweiz": "Industrieland",
  "Vereinigtes Königreich": "Industrieland",
  "Andorra": "Industrieland",
  "Italien": "Industrieland",
  "San Marino": "Industrieland",
  "Schweden": "Industrieland",
  "Slowakei": "Schwellenland",
  "Slowenien": "Schwellenland",
  "Spanien": "Industrieland",
  "Ungarn": "Schwellenland",
  "Vatikanstadt": "Industrieland",
  "Zypern": "Schwellenland",
  "Malta": "Industrieland",
  "Rumänien": "Schwellenland",
  "Litauen": "Schwellenland",
  "Estland": "Schwellenland",
  "Portugal": "Industrieland",
  "Irland": "Industrieland",
  "Griechenland": "Industrieland",
  "Kroatien": "Schwellenland",
  "Lettland": "Schwellenland",
  "Bulgarien": "Schwellenland",
  "Albanien": "Entwicklungsland",
  "Bosnien-Herzegowina": "Entwicklungsland",
  "Färöer": "Industrieland",
  "Grönland": "Industrieland",
  "Island": "Industrieland",
  "Nordmazedonien": "Entwicklungsland",
  "Montenegro": "Entwicklungsland",
  "Norwegen": "Industrieland",
  "Republik Moldau": "Entwicklungsland",
  "Serbien": "Entwicklungsland",
  "Ukraine": "Entwicklungsland",
  "Weißrussland": "Entwicklungsland",
  "Ägypten": "Entwicklungsland",
  "Algerien": "Entwicklungsland",
  "Georgien": "Entwicklungsland",
  "Israel": "Industrieland",
  "Libanon": "Entwicklungsland",
  "Libyen": "Entwicklungsland",
  "Marokko": "Entwicklungsland",
  "Russische Föderation": "Schwellenland",
  "Syrien": "Entwicklungsland",
  "Tunesien": "Entwicklungsland",
  "Türkei": "Schwellenland",
  "Afghanistan": "Entwicklungsland",
  "Armenien": "Entwicklungsland",
  "Aserbaidschan": "Entwicklungsland",
  "Bahrain": "Schwellenland",
  "Bangladesch": "Entwicklungsland",
  "Bhutan": "Entwicklungsland",
  "Brunei Darussalam": "Schwellenland",
  "China": "Schwellenland",
  "Indien": "Schwellenland",
  "Indonesien": "Schwellenland",
  "Irak": "Entwicklungsland",
  "Iran": "Schwellenland",
  "Japan": "Industrieland",
  "Jemen": "Entwicklungsland",
  "Jordanien": "Entwicklungsland",
  "Kambodscha": "Entwicklungsland",
  "Kanada": "Industrieland",
  "Kasachstan": "Entwicklungsland",
  "Katar": "Industrieland",
  "Kirgisistan": "Entwicklungsland",
  "Kuwait": "Industrieland",
  "Laos": "Entwicklungsland",
  "Malaysia": "Schwellenland",
  "Malediven": "Entwicklungsland",
  "Mexiko": "Schwellenland",
  "Mongolei": "Entwicklungsland",
  "Myanmar": "Entwicklungsland",
  "Nepal": "Entwicklungsland",
  "Nordkorea": "Entwicklungsland",
  "Oman": "Schwellenland",
  "Osttimor": "Entwicklungsland",
  "Pakistan": "Entwicklungsland",
  "Papua-Neuguinea": "Entwicklungsland",
  "Philippinen": "Schwellenland",
  "Saudi-Arabien": "Industrieland",
  "Singapur": "Industrieland",
  "Sri Lanka": "Entwicklungsland",
  "Südkorea": "Industrieland",
  "Tadschikistan": "Entwicklungsland",
  "Taiwan": "Industrieland",
  "Thailand": "Schwellenland",
  "Turkmenistan": "Entwicklungsland",
  "USA": "Industrieland",
  "Usbekistan": "Entwicklungsland",
  "Vereinigte Arabische Emirate": "Industrieland",
  "Vietnam": "Schwellenland",
  "Australien": "Industrieland",
  "Neuseeland": "Industrieland",
  "Südafrika": "Schwellenland",
  "Finnland": "Industrieland"
};

export const kostenNachKategorie = {
  "Industrieland": {
    umverpackung: 6,
    inlandWeiterleitung: 6
  },
  "Schwellenland": {
    umverpackung: 8,
    inlandWeiterleitung: 8
  },
  "Entwicklungsland": {
    umverpackung: 10,
    inlandWeiterleitung: 10
  }
};
