const speditionsdaten = [
  { Land: "Südafrika", Preis_EUR: 650, Richtwert_50: 623 },
  { Land: "Brasilien", Preis_EUR: 1400, Richtwert_50: 1200 },
  { Land: "Kanada", Preis_EUR: 576, Richtwert_50: 410 },
  { Land: "Japan", Preis_EUR: 400, Richtwert_50: 250 },
  { Land: "Australien", Preis_EUR: 600, Richtwert_50: 565 },
  { Land: "USA", Preis_EUR: 630, Richtwert_50: 480 },
  { Land: "Neuseeland", Preis_EUR: 406, Richtwert_50: 372 },
  { Land: "China", Preis_EUR: 350, Richtwert_50: 270 },
  { Land: "Indien", Preis_EUR: 380, Richtwert_50: 350 },
  { Land: "Marokko", Preis_EUR: 600 },
  { Land: "Schweiz", Preis_EUR: 176 },
  { Land: "Portugal", Preis_EUR: 201 },
  { Land: "Finnland", Preis_EUR: 163 },
  { Land: "Dänemark", Preis_EUR: 147 },
  { Land: "Israel", Preis_EUR: 1000, Richtwert_50: 1000 },
  { Land: "Spanien", Preis_EUR: 187 },
  { Land: "Schweden", Preis_EUR: 170 },
  { Land: "Frankreich", Preis_EUR: 144 },
  { Land: "Italien", Preis_EUR: 170 },
  { Land: "Luxemburg", Preis_EUR: 125 },
  { Land: "Irland", Preis_EUR: 250 },
  { Land: "Monaco", Preis_EUR: 280 },
  { Land: "Ungarn", Preis_EUR: 117 },
  { Land: "Russland", Preis_EUR: 600 },
  { Land: "Türkei", Preis_EUR: 315 },
  { Land: "Rumänien", Preis_EUR: 150 },
  { Land: "Belgien", Preis_EUR: 140 },
  { Land: "Österreich", Preis_EUR: 120 },
  { Land: "Niederlande", Preis_EUR: 150 },
  { Land: "Polen", Preis_EUR: 130 },
  { Land: "Thailand", Preis_EUR: 410, Richtwert_50: 335 },
  { Land: "Indonesien", Preis_EUR: 400, Richtwert_50: 318 },
  { Land: "Mexiko", Preis_EUR: 624 },
  { Land: "Südkorea", Preis_EUR: 365, Richtwert_50: 300 },
  { Land: "Ägypten", Preis_EUR: 640 },
  { Land: "Singapur", Preis_EUR: 340, Richtwert_50: 214 },
  { Land: "Philippinen", Preis_EUR: 406 },
  { Land: "Abu-Dhabi", Preis_EUR: 470 },
  { Land: "Vietnam", Preis_EUR: 380 },
  { Land: "Chile", Preis_EUR: 1315 },
  { Land: "Argentinien", Preis_EUR: 1050 },
  { Land: "Tschechien", Preis_EUR: 100 },
  { Land: "Griechenland", Preis_EUR: 290 },
  { Land: "Vereinigtes Königreich", Preis_EUR: 195 },
  { Land: "England", Preis_EUR: 195 }
];

export default speditionsdaten;
