const zones = {
  "Belgien": "Zone 1 – EU",
  "Dänemark": "Zone 1 – EU",
  "Frankreich": "Zone 1 – EU",
  "Luxemburg": "Zone 1 – EU",
  "Monaco": "Zone 1 – EU",
  "Niederlande": "Zone 1 – EU",
  "Österreich": "Zone 1 – EU",
  "Polen": "Zone 1 – EU",
  "Tschechische Republik": "Zone 1 – EU",
  "Liechtenstein": "Zone 1 – non EU",
  "Schweiz": "Zone 1 – non EU",
  "Vereinigtes Königreich": "Zone 1 – non EU",
  "Andorra": "Zone 2 – EU/non EU",
  "Italien": "Zone 2 – EU/non EU",
  "San Marino": "Zone 2 – EU/non EU",
  "Schweden": "Zone 2 – EU/non EU",
  "Slowakei": "Zone 2 – EU/non EU",
  "Slowenien": "Zone 2 – EU/non EU",
  "Spanien": "Zone 2 – EU/non EU",
  "Ungarn": "Zone 2 – EU/non EU",
  "Vatikanstadt": "Zone 2 – EU/non EU",
  "Zypern": "Zone 2 – EU/non EU",
  "Malta": "Zone 2 – EU/non EU",
  "Rumänien": "Zone 2 – EU/non EU",
  "Litauen": "Zone 2 – EU/non EU",
  "Estland": "Zone 2 – EU/non EU",
  "Portugal": "Zone 2 – EU/non EU",
  "Irland": "Zone 2 – EU/non EU",
  "Griechenland": "Zone 2 – EU/non EU",
  "Kroatien": "Zone 2 – EU/non EU",
  "Lettland": "Zone 2 – EU/non EU",
  "Bulgarien": "Zone 2 – EU/non EU",
  "Albanien": "Zone 3 – non EU",
  "Bosnien-Herzegowina": "Zone 3 – non EU",
  "Färöer": "Zone 3 – non EU",
  "Grönland": "Zone 3 – non EU",
  "Island": "Zone 3 – non EU",
  "Nordmazedonien": "Zone 3 – non EU",
  "Montenegro": "Zone 3 – non EU",
  "Norwegen": "Zone 3 – non EU",
  "Republik Moldau": "Zone 3 – non EU",
  "Serbien": "Zone 3 – non EU",
  "Ukraine": "Zone 3 – non EU",
  "Weißrussland": "Zone 3 – non EU",
  "Ägypten": "Zone 4 – non EU",
  "Algerien": "Zone 4 – non EU",
  "Georgien": "Zone 4 – non EU",
  "Israel": "Zone 4 – non EU",
  "Libanon": "Zone 4 – non EU",
  "Libyen": "Zone 4 – non EU",
  "Marokko": "Zone 4 – non EU",
  "Russische Föderation": "Zone 4 – non EU",
  "Syrien": "Zone 4 – non EU",
  "Tunesien": "Zone 4 – non EU",
  "Türkei": "Zone 4 – non EU",
  "Afghanistan": "Zone 5 – non EU",
  "Armenien": "Zone 5 – non EU",
  "Aserbaidschan": "Zone 5 – non EU",
  "Bahrain": "Zone 5 – non EU",
  "Bangladesch": "Zone 5 – non EU",
  "Bhutan": "Zone 5 – non EU",
  "Brunei Darussalam": "Zone 5 – non EU",
  "China": "Zone 5 – non EU",
  "Indien": "Zone 5 – non EU",
  "Indonesien": "Zone 5 – non EU",
  "Irak": "Zone 5 – non EU",
  "Iran": "Zone 5 – non EU",
  "Japan": "Zone 5 – non EU",
  "Jemen": "Zone 5 – non EU",
  "Jordanien": "Zone 5 – non EU",
  "Kambodscha": "Zone 5 – non EU",
  "Kanada": "Zone 5 – non EU",
  "Kasachstan": "Zone 5 – non EU",
  "Katar": "Zone 5 – non EU",
  "Kirgisistan": "Zone 5 – non EU",
  "Kuwait": "Zone 5 – non EU",
  "Laos": "Zone 5 – non EU",
  "Malaysia": "Zone 5 – non EU",
  "Malediven": "Zone 5 – non EU",
  "Mexiko": "Zone 5 – non EU",
  "Mongolei": "Zone 5 – non EU",
  "Myanmar": "Zone 5 – non EU",
  "Nepal": "Zone 5 – non EU",
  "Nordkorea": "Zone 5 – non EU",
  "Oman": "Zone 5 – non EU",
  "Osttimor": "Zone 5 – non EU",
  "Pakistan": "Zone 5 – non EU",
  "Papua-Neuguinea": "Zone 5 – non EU",
  "Philippinen": "Zone 5 – non EU",
  "Saudi-Arabien": "Zone 5 – non EU",
  "Singapur": "Zone 5 – non EU",
  "Sri Lanka": "Zone 5 – non EU",
  "Südkorea": "Zone 5 – non EU",
  "Tadschikistan": "Zone 5 – non EU",
  "Taiwan": "Zone 5 – non EU",
  "Thailand": "Zone 5 – non EU",
  "Turkmenistan": "Zone 5 – non EU",
  "USA": "Zone 5 – non EU",
  "Usbekistan": "Zone 5 – non EU",
  "Vereinigte Arabische Emirate": "Zone 5 – non EU",
  "Vietnam": "Zone 5 – non EU",
  "Australien": "Zone 6 – non EU",
  "Neuseeland": "Zone 6 – non EU",
  "Südafrika": "Zone 6 – non EU",
  "Finnland": "Zone 3 – EU"
};

export default zones;
